### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by testQAacademy** [testQAacademy/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by AndrewMax1** [comment]
My name Ryu, I'm a fighter.  After defeating Sagat and M. Bison for the nth time, I’ve decided to downshift my martial arts career a little bit and get into this IT thing ― sensei tells me that there’s a lot of money on the Internet, and a whole lot less getting punched in the face. I’d like to build a little website to market my personal brand, then maybe sell a few t-shirts, nunchucks, that sort of thing ― I think it’ll be a big hit.

**Comment by testQAacademy** [comment]
Ok
